#!/bin/bash


set -e

cd "$(dirname "$(readlink -f -- "$0")")"

# source .env
set -a
if [ -f .env ]; then
    source .env
fi
set +a

# source the python venv if exist
if [ -n "${PYTHON_VENV}" ]; then
    if [ -f "${PYTHON_VENV}/bin/activate" ]; then
        source "${PYTHON_VENV}/bin/activate"
    fi
fi

export PYTHONPATH=.

python3 utils/update_sig_checks.py 1
npx hardhat test
python3 utils/update_sig_checks.py 0