/**
 * Wrap diamondCut calldata as timelock schedule + execute transactions.
 *
 * Reads diamondcut-calldata.json (output of generateSafeBatch.ts), fetches
 * minDelay from the timelock contract, and outputs two Safe batches:
 *   1. timelock-schedule-safe-batch.json  -- schedule() call, execute immediately
 *   2. timelock-execute-safe-batch.json   -- execute() call, submit after delay
 *
 * Usage:
 *   npx hardhat run scripts/upgrade/generateTimelockBatch.ts --network mantle
 *
 * Config: scripts/upgrade/config/upgrade.json (timelockAddress field)
 * Env overrides: TIMELOCK_ADDRESS, DIAMOND_ADDRESS, SAFE_ADDRESS
 */
import fs from "fs"
import path from "path"

import { ethers } from "../../test/helpers/hardhat-connection.js"
import { verifyRpc } from "./utils/rpcCheck.js"
import type { SafeBatch } from "./utils/upgradeHelpers.js"

type Config = {
	diamondAddress?: string
	safeAddress?: string
	timelockAddress?: string
}

const TIMELOCK_ABI = [
	"function getMinDelay() view returns (uint256)",
	"function schedule(address target, uint256 value, bytes data, bytes32 predecessor, bytes32 salt, uint256 delay)",
	"function execute(address target, uint256 value, bytes payload, bytes32 predecessor, bytes32 salt) payable",
	"function hashOperation(address target, uint256 value, bytes data, bytes32 predecessor, bytes32 salt) pure returns (bytes32)",
]

const CONFIG_FILE = process.env.UPGRADE_CONFIG_FILE ?? "./scripts/upgrade/config/upgrade.json"
const OUTPUT_DIR = "./scripts/upgrade/output"
const ZERO_BYTES32 = ethers.ZeroHash

function loadConfig(): Config {
	if (!fs.existsSync(CONFIG_FILE)) return {}
	return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf-8")) as Config
}

function formatDuration(seconds: number): string {
	if (seconds < 60) return `${seconds}s`
	if (seconds < 3600) return `${Math.floor(seconds / 60)}m`
	const hours = Math.floor(seconds / 3600)
	const mins = Math.floor((seconds % 3600) / 60)
	return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`
}

function makeSafeBatch(chainId: string, safeAddress: string, name: string, txs: { to: string; value: string; data: string }[]): SafeBatch {
	return {
		version: "1.0",
		chainId,
		createdAt: Date.now(),
		meta: {
			name,
			description: `Generated by scripts/upgrade/generateTimelockBatch.ts`,
			txBuilderVersion: "1.18.0",
			createdFromSafeAddress: safeAddress,
			createdFromOwnerAddress: "",
		},
		transactions: txs,
	}
}

async function main() {
	await verifyRpc()
	const config = loadConfig()

	const DIAMOND_ADDRESS = process.env.DIAMOND_ADDRESS ?? config.diamondAddress
	const SAFE_ADDRESS = process.env.SAFE_ADDRESS ?? config.safeAddress
	const TIMELOCK_ADDRESS = process.env.TIMELOCK_ADDRESS ?? config.timelockAddress
	const CHAIN_ID = String(Number((await ethers.provider.getNetwork()).chainId))

	if (!DIAMOND_ADDRESS || !ethers.isAddress(DIAMOND_ADDRESS)) throw new Error("DIAMOND_ADDRESS required")
	if (!SAFE_ADDRESS || !ethers.isAddress(SAFE_ADDRESS)) throw new Error("SAFE_ADDRESS required")
	if (!TIMELOCK_ADDRESS || !ethers.isAddress(TIMELOCK_ADDRESS))
		throw new Error("TIMELOCK_ADDRESS required (config timelockAddress or env TIMELOCK_ADDRESS)")

	// Load diamondcut calldata
	const calldataFile = path.join(OUTPUT_DIR, "diamondcut-calldata.json")
	if (!fs.existsSync(calldataFile)) throw new Error(`${calldataFile} not found — run generateSafeBatch.ts first`)
	const calldataJson = JSON.parse(fs.readFileSync(calldataFile, "utf-8"))
	const chunks: { calldata: string; description: string }[] = calldataJson.chunks
	if (!chunks || chunks.length === 0) throw new Error("No diamondCut calldata chunks found")

	console.log(`Diamond:    ${DIAMOND_ADDRESS}`)
	console.log(`Timelock:   ${TIMELOCK_ADDRESS}`)
	console.log(`Safe:       ${SAFE_ADDRESS}`)
	console.log(`Chain ID:   ${CHAIN_ID}`)
	console.log(`Chunks:     ${chunks.length}`)
	console.log()

	// Fetch minDelay from timelock
	const timelock = new ethers.Contract(TIMELOCK_ADDRESS, TIMELOCK_ABI, ethers.provider)
	const minDelay = await timelock.getMinDelay()
	console.log(`Min delay:  ${minDelay} (${formatDuration(Number(minDelay))})`)
	console.log()

	const timelockIface = new ethers.Interface(TIMELOCK_ABI)

	// Write output
	if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true })

	// Remove any previously generated per-chunk files so old chunks don't leak in
	// (safe because we rewrite them all below)
	for (const f of fs.readdirSync(OUTPUT_DIR)) {
		if (/^timelock-(schedule|execute)-safe-batch(-\d+)?\.json$/.test(f)) {
			fs.unlinkSync(path.join(OUTPUT_DIR, f))
		}
	}

	const scheduleFiles: string[] = []
	const executeFiles: string[] = []
	const pad = String(chunks.length).length

	// For each chunk: unique salt, chained predecessor (chunk N depends on chunk N-1),
	// so the timelock enforces strict in-order execution.
	// One Safe batch file per chunk so each Ledger signing prompt only sees one
	// schedule()/execute() call (multicall aggregation of N txs would blow the Ledger
	// calldata limit).
	let predecessor: string = ZERO_BYTES32
	for (let i = 0; i < chunks.length; i++) {
		const chunkCalldata = chunks[i].calldata
		const salt = ethers.keccak256(
			ethers.AbiCoder.defaultAbiCoder().encode(
				["uint256", "address", "string", "uint256"],
				[BigInt(CHAIN_ID), DIAMOND_ADDRESS, "diamondCut-v0.8.5", BigInt(i)],
			),
		)
		const operationId = await timelock.hashOperation(DIAMOND_ADDRESS, 0, chunkCalldata, predecessor, salt)

		const bytes = (chunkCalldata.length - 2) / 2
		console.log(`Chunk ${i + 1}/${chunks.length}:`)
		console.log(`  size:        ${bytes} bytes (${(bytes / 1024).toFixed(2)} KB)`)
		console.log(`  salt:        ${salt}`)
		console.log(`  predecessor: ${predecessor}`)
		console.log(`  operation:   ${operationId}`)

		const scheduleTx = {
			to: TIMELOCK_ADDRESS,
			value: "0",
			data: timelockIface.encodeFunctionData("schedule", [DIAMOND_ADDRESS, 0, chunkCalldata, predecessor, salt, minDelay]),
		}
		const executeTx = {
			to: TIMELOCK_ADDRESS,
			value: "0",
			data: timelockIface.encodeFunctionData("execute", [DIAMOND_ADDRESS, 0, chunkCalldata, predecessor, salt]),
		}

		const idx = String(i + 1).padStart(pad, "0")
		const scheduleFile = path.join(OUTPUT_DIR, `timelock-schedule-safe-batch-${idx}.json`)
		const executeFile = path.join(OUTPUT_DIR, `timelock-execute-safe-batch-${idx}.json`)

		const scheduleBatch = makeSafeBatch(
			CHAIN_ID,
			SAFE_ADDRESS,
			`Symmio v0.8.5 — Timelock Schedule DiamondCut chunk ${i + 1}/${chunks.length}`,
			[scheduleTx],
		)
		fs.writeFileSync(scheduleFile, JSON.stringify(scheduleBatch, null, 2))
		scheduleFiles.push(scheduleFile)

		const executeBatch = makeSafeBatch(
			CHAIN_ID,
			SAFE_ADDRESS,
			`Symmio v0.8.5 — Timelock Execute DiamondCut chunk ${i + 1}/${chunks.length}`,
			[executeTx],
		)
		fs.writeFileSync(executeFile, JSON.stringify(executeBatch, null, 2))
		executeFiles.push(executeFile)

		predecessor = operationId
	}
	console.log()

	console.log(`Schedule files (${scheduleFiles.length}):`)
	for (const f of scheduleFiles) console.log(`  ${f}`)
	console.log(`Execute files  (${executeFiles.length}):`)
	for (const f of executeFiles) console.log(`  ${f}`)

	console.log(`\nWorkflow:`)
	console.log(`  1. Import each timelock-schedule-safe-batch-N.json into Safe TX Builder in order`)
	console.log(`     (chunks share a predecessor chain — must be scheduled in order 1..${chunks.length})`)
	console.log(`  2. Wait ${formatDuration(Number(minDelay))}`)
	console.log(`  3. Import each timelock-execute-safe-batch-N.json into Safe TX Builder in order`)
	console.log(`     (strict ordering enforced on-chain by the predecessor chain)`)
}

main().catch(error => {
	console.error(error)
	process.exitCode = 1
})
