/**
 * Wrap diamondCut calldata as timelock schedule + execute transactions.
 *
 * Reads diamondcut-calldata.json (output of generateSafeBatch.ts), fetches
 * minDelay from the timelock contract, and outputs two Safe batches:
 *   1. timelock-schedule-safe-batch.json  -- schedule() call, execute immediately
 *   2. timelock-execute-safe-batch.json   -- execute() call, submit after delay
 *
 * Usage:
 *   npx hardhat run scripts/upgrade/generateTimelockBatch.ts --network mantle
 *
 * Config: scripts/upgrade/config/upgrade.json (timelockAddress field)
 * Env overrides: TIMELOCK_ADDRESS, DIAMOND_ADDRESS, SAFE_ADDRESS
 */
import fs from "fs"
import path from "path"

import { ethers } from "../../test/helpers/hardhat-connection.js"
import { verifyRpc } from "./utils/rpcCheck.js"
import type { SafeBatch } from "./utils/upgradeHelpers.js"

type Config = {
	diamondAddress?: string
	safeAddress?: string
	timelockAddress?: string
}

const TIMELOCK_ABI = [
	"function getMinDelay() view returns (uint256)",
	"function schedule(address target, uint256 value, bytes data, bytes32 predecessor, bytes32 salt, uint256 delay)",
	"function execute(address target, uint256 value, bytes payload, bytes32 predecessor, bytes32 salt) payable",
	"function hashOperation(address target, uint256 value, bytes data, bytes32 predecessor, bytes32 salt) pure returns (bytes32)",
]

const CONFIG_FILE = process.env.UPGRADE_CONFIG_FILE ?? "./scripts/upgrade/config/upgrade.json"
const OUTPUT_DIR = "./scripts/upgrade/output"
const ZERO_BYTES32 = ethers.ZeroHash

function loadConfig(): Config {
	if (!fs.existsSync(CONFIG_FILE)) return {}
	return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf-8")) as Config
}

function formatDuration(seconds: number): string {
	if (seconds < 60) return `${seconds}s`
	if (seconds < 3600) return `${Math.floor(seconds / 60)}m`
	const hours = Math.floor(seconds / 3600)
	const mins = Math.floor((seconds % 3600) / 60)
	return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`
}

function makeSafeBatch(chainId: string, safeAddress: string, name: string, txs: { to: string; value: string; data: string }[]): SafeBatch {
	return {
		version: "1.0",
		chainId,
		createdAt: Date.now(),
		meta: {
			name,
			description: `Generated by scripts/upgrade/generateTimelockBatch.ts`,
			txBuilderVersion: "1.18.0",
			createdFromSafeAddress: safeAddress,
			createdFromOwnerAddress: "",
		},
		transactions: txs,
	}
}

async function main() {
	await verifyRpc()
	const config = loadConfig()

	const DIAMOND_ADDRESS = process.env.DIAMOND_ADDRESS ?? config.diamondAddress
	const SAFE_ADDRESS = process.env.SAFE_ADDRESS ?? config.safeAddress
	const TIMELOCK_ADDRESS = process.env.TIMELOCK_ADDRESS ?? config.timelockAddress
	const CHAIN_ID = String(Number((await ethers.provider.getNetwork()).chainId))

	if (!DIAMOND_ADDRESS || !ethers.isAddress(DIAMOND_ADDRESS)) throw new Error("DIAMOND_ADDRESS required")
	if (!SAFE_ADDRESS || !ethers.isAddress(SAFE_ADDRESS)) throw new Error("SAFE_ADDRESS required")
	if (!TIMELOCK_ADDRESS || !ethers.isAddress(TIMELOCK_ADDRESS))
		throw new Error("TIMELOCK_ADDRESS required (config timelockAddress or env TIMELOCK_ADDRESS)")

	// Load diamondcut calldata
	const calldataFile = path.join(OUTPUT_DIR, "diamondcut-calldata.json")
	if (!fs.existsSync(calldataFile)) throw new Error(`${calldataFile} not found — run generateSafeBatch.ts first`)
	const calldataJson = JSON.parse(fs.readFileSync(calldataFile, "utf-8"))
	const chunks: { calldata: string; description: string }[] = calldataJson.chunks
	if (!chunks || chunks.length === 0) throw new Error("No diamondCut calldata chunks found")
	if (chunks.length > 1) console.warn(`WARN: ${chunks.length} chunks found — wrapping all, but expected 1`)

	const diamondCutCalldata = chunks[0].calldata

	console.log(`Diamond:    ${DIAMOND_ADDRESS}`)
	console.log(`Timelock:   ${TIMELOCK_ADDRESS}`)
	console.log(`Safe:       ${SAFE_ADDRESS}`)
	console.log(`Chain ID:   ${CHAIN_ID}`)
	console.log()

	// Fetch minDelay from timelock
	const timelock = new ethers.Contract(TIMELOCK_ADDRESS, TIMELOCK_ABI, ethers.provider)
	const minDelay = await timelock.getMinDelay()
	console.log(`Min delay:  ${minDelay} (${formatDuration(Number(minDelay))})`)

	// Deterministic salt
	const salt = ethers.keccak256(
		ethers.AbiCoder.defaultAbiCoder().encode(["uint256", "address", "string"], [BigInt(CHAIN_ID), DIAMOND_ADDRESS, "diamondCut-v0.8.5"]),
	)
	console.log(`Salt:       ${salt}`)

	// Compute operation ID
	const operationId = await timelock.hashOperation(DIAMOND_ADDRESS, 0, diamondCutCalldata, ZERO_BYTES32, salt)
	console.log(`Operation:  ${operationId}`)
	console.log()

	// Encode schedule and execute
	const timelockIface = new ethers.Interface(TIMELOCK_ABI)

	const scheduleCalldata = timelockIface.encodeFunctionData("schedule", [DIAMOND_ADDRESS, 0, diamondCutCalldata, ZERO_BYTES32, salt, minDelay])

	const executeCalldata = timelockIface.encodeFunctionData("execute", [DIAMOND_ADDRESS, 0, diamondCutCalldata, ZERO_BYTES32, salt])

	// Write output
	if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true })

	const scheduleBatch = makeSafeBatch(CHAIN_ID, SAFE_ADDRESS, "Symmio v0.8.5 — Timelock Schedule DiamondCut", [
		{ to: TIMELOCK_ADDRESS, value: "0", data: scheduleCalldata },
	])
	const scheduleFile = path.join(OUTPUT_DIR, "timelock-schedule-safe-batch.json")
	fs.writeFileSync(scheduleFile, JSON.stringify(scheduleBatch, null, 2))
	console.log(`Schedule batch: ${scheduleFile}`)

	const executeBatch = makeSafeBatch(CHAIN_ID, SAFE_ADDRESS, "Symmio v0.8.5 — Timelock Execute DiamondCut", [
		{ to: TIMELOCK_ADDRESS, value: "0", data: executeCalldata },
	])
	const executeFile = path.join(OUTPUT_DIR, "timelock-execute-safe-batch.json")
	fs.writeFileSync(executeFile, JSON.stringify(executeBatch, null, 2))
	console.log(`Execute batch:  ${executeFile}`)

	console.log(`\nWorkflow:`)
	console.log(`  1. Import ${path.basename(scheduleFile)} into Safe TX Builder → execute now`)
	console.log(`  2. Wait ${formatDuration(Number(minDelay))}`)
	console.log(`  3. Import ${path.basename(executeFile)} into Safe TX Builder → execute after delay`)
}

main().catch(error => {
	console.error(error)
	process.exitCode = 1
})
