/** Core-only pause roles. AccountLayer and helper contracts retain their own PAUSER_ROLE. */
export const CORE_PAUSE_ROLES = [
	"GLOBAL_PAUSER_ROLE",
	"PARTY_A_PAUSER_ROLE",
	"PARTY_B_PAUSER_ROLE",
	"ACCOUNTING_PAUSER_ROLE",
	"INTERNAL_TRANSFER_PAUSER_ROLE",
	"EXTERNAL_TRANSFER_PAUSER_ROLE",
	"LIQUIDATION_PAUSER_ROLE",
	"INSTANT_LAYER_PAUSER_ROLE",
	"WITHDRAW_ADVANCE_PAUSER_ROLE",
] as const
