#!/bin/sh

# Check if any .sol files are staged
if git diff --cached --name-only | grep -q '\.sol$'; then
    echo "Solidity files changed. Compiling and regenerating ABIs..."

    # Compile contracts
    npx hardhat compile
    if [ $? -ne 0 ]; then
        echo "Compilation failed. Aborting commit."
        exit 1
    fi

    # Generate ABIs
    python3 ./utils/make_abi.py
    if [ $? -ne 0 ]; then
        echo "ABI generation failed. Aborting commit."
        exit 1
    fi

    # Stage the updated ABI files
    git add abis/

    echo "ABIs updated and staged."
fi

# Run prettier checks
echo "Formatting Solidity files..."
npm run prettier:contracts

echo "Formatting TypeScript files..."
npm run prettier:ts

# Stage any formatting changes
git add -u
